
import { Language } from './types';

type Translations = {
  [key in Language]: {
    appTitle: string;
    appSubtitle: string;
    sourceMaterial: string;
    dropFile: string;
    additionalContext: string;
    contextPlaceholder: string;
    createAgenda: string;
    generating: string;
    agendaReady: string;
    totalDuration: string;
    autoGenerated: string;
    attendees: string;
    lead: string;
    workspace: string;
    showAssistant: string;
    hideAssistant: string;
    readyToBuild: string;
    readyDescription: string;
    analyzing: string;
    identifying: string;
    failedError: string;
    agendaAssistant: string;
    askPlaceholder: string;
    footer: string;
    initChat: string;
    chatReady: string;
    chatError: string;
    chatProcessingError: string;
    tellMeMore: string;
    severity: string;
    action: string;
    costEst: string;
    selectModel: string;
    providerGoogle: string;
    providerMistral: string;
    modelError: string;
    enterApiKey: string;
    apiKeyPlaceholder: string;
    apiKeyNote: string;
    exportPdf: string;
    evidenceGallery: string;
    filesAttached: string;
    addMore: string;
    caseEvidence: string;
    visualEvidence: string;
    documents: string;
    noEvidence: string;
    uploadAdditional: string;
    viewFullGallery: string;
    analysisReport: string;
    damageVisualization: string;
    interactiveMap: string;
    fileDetails: string;
    fileSize: string;
    dateModified: string;
    cameraInfo: string;
    cameraModel: string;
    cameraSettings: string;
  }
};

export const translations: Translations = {
  en: {
    appTitle: "CarCrashGenius",
    appSubtitle: "AI Insurance Adjuster",
    sourceMaterial: "Evidence Files",
    dropFile: "Drop photos or docs here\n(JPG, PNG, PDF, TXT)",
    additionalContext: "Incident Details",
    contextPlaceholder: "E.g. Speed approx 30mph, hit by SUV from right side...",
    createAgenda: "Analyze Evidence",
    generating: "Analyzing...",
    agendaReady: "Report ready. Check the main view.",
    totalDuration: "points of impact",
    autoGenerated: "AI Assessment",
    attendees: "Vehicles Identified",
    lead: "Part:",
    workspace: "Claims Desk",
    showAssistant: "Chat",
    hideAssistant: "Hide",
    readyToBuild: "Ready to assess damage",
    readyDescription: "Upload multiple photos or official documents (PDF/TXT) of the accident to automatically identify damage, estimate repair complexity, and generate an independent report.",
    analyzing: "Processing Evidence",
    identifying: "Cross-referencing docs and visual damage...",
    failedError: "Failed to analyze evidence. Please ensure files are clear.",
    agendaAssistant: "Claims Assistant",
    askPlaceholder: "Ask about coverage, costs...",
    footer: "Gemini 3 Pro Preview • Estimates are for reference only",
    initChat: "Initializing Adjuster...",
    chatReady: "I've reviewed the crash data for \"{title}\". Ask me about repairs or insurance specifics.",
    chatError: "Connection error. Please try analyzing again.",
    chatProcessingError: "Sorry, I ran into an issue processing that request.",
    tellMeMore: "Explain the damage to:",
    severity: "Severity",
    action: "Action",
    costEst: "Est. Cost",
    selectModel: "AI Model",
    providerGoogle: "Google AI",
    providerMistral: "Mistral AI",
    modelError: "Provider not configured. Please select a Google model.",
    enterApiKey: "Mistral API Key",
    apiKeyPlaceholder: "Enter key...",
    apiKeyNote: "Stored locally in browser",
    exportPdf: "Export PDF",
    evidenceGallery: "Evidence Gallery",
    filesAttached: "Files Attached",
    addMore: "Add Files",
    caseEvidence: "Case Evidence",
    visualEvidence: "Visual Evidence",
    documents: "Documents",
    noEvidence: "No evidence files attached to this case.",
    uploadAdditional: "Upload Additional Evidence",
    viewFullGallery: "View Full Gallery",
    analysisReport: "Analysis Report",
    damageVisualization: "Visual Analysis",
    interactiveMap: "Interactive Damage Map",
    fileDetails: "File Metadata",
    fileSize: "Size",
    dateModified: "Date",
    cameraInfo: "Camera Info",
    cameraModel: "Model",
    cameraSettings: "Shot Settings",
  },
  ru: {
    appTitle: "CarCrashGenius",
    appSubtitle: "ИИ Страховой Эксперт",
    sourceMaterial: "Файлы доказательств",
    dropFile: "Перетащите фото или доки\n(JPG, PNG, PDF, TXT)",
    additionalContext: "Детали происшествия",
    contextPlaceholder: "Например: скорость 50 км/ч, удар справа от внедорожника...",
    createAgenda: "Анализ данных",
    generating: "Оценка...",
    agendaReady: "Отчет готов. Проверьте главный экран.",
    totalDuration: "точек удара",
    autoGenerated: "ИИ Оценка",
    attendees: "Опознанные ТС",
    lead: "Деталь:",
    workspace: "Рабочий стол",
    showAssistant: "Чат",
    hideAssistant: "Скрыть",
    readyToBuild: "Готов к оценке ущерба",
    readyDescription: "Загрузите фотографии или официальные документы (PDF/TXT) об аварии, чтобы автоматически определить повреждения и оценить ремонт.",
    analyzing: "Сканирование",
    identifying: "Анализ документов и повреждений...",
    failedError: "Не удалось проанализировать данные.",
    agendaAssistant: "Ассистент по убыткам",
    askPlaceholder: "Спросите о стоимости, запчастях...",
    footer: "Gemini 3 Pro Preview • Оценки носят справочный характер",
    initChat: "Инициализация эксперта...",
    chatReady: "Я изучил данные ДТП: \"{title}\". Спрашивайте о ремонте или страховых нюансах.",
    chatError: "Ошибка соединения. Попробуйте снова.",
    chatProcessingError: "Извините, возникла проблема при обработке запроса.",
    tellMeMore: "Разъясни повреждение:",
    severity: "Тяжесть",
    action: "Решение",
    costEst: "Оценка ремонта",
    selectModel: "AI Модель",
    providerGoogle: "Google AI",
    providerMistral: "Mistral AI",
    modelError: "Провайдер не настроен. Пожалуйста, выберите модель Google.",
    enterApiKey: "Mistral API Key",
    apiKeyPlaceholder: "Введите ключ...",
    apiKeyNote: "Хранится локально в браузере",
    exportPdf: "Скачать PDF",
    evidenceGallery: "Галерея доказательств",
    filesAttached: "Файлов прикреплено",
    addMore: "Добавить",
    caseEvidence: "Материалы дела",
    visualEvidence: "Фотофиксация",
    documents: "Документы",
    noEvidence: "Нет прикрепленных файлов.",
    uploadAdditional: "Загрузить материалы",
    viewFullGallery: "Открыть галерею",
    analysisReport: "Отчет об анализе",
    damageVisualization: "Визуальный анализ",
    interactiveMap: "Интерактивная карта повреждений",
    fileDetails: "Метаданные файла",
    fileSize: "Размер",
    dateModified: "Дата",
    cameraInfo: "Данные камеры",
    cameraModel: "Модель",
    cameraSettings: "Настройки съемки",
  }
};
